version: '3'
services:

  app:
    build: .
    expose:
      - 8000
    volumes:
      - static:/app/static:rw
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx:rw
      - static:/app/static:ro
    depends_on:
      - app

volumes:
  static:
